[package]
name = "polkadot-archive"
version = "0.2.4"
authors = ["Andrew Plaza <aplaza@liquidthink.net>"]
edition = "2018"
description = "Indexes the Polkadot, Kusama and Westend Networks"

[dependencies]
anyhow = "1.0"
clap = { version = "2.33.1", features = ["yaml", "suggestions", "color"] }
ctrlc = { version = "3.1.5", features = ["termination"] }
log = "0.4"
serde = "1.0"
structopt = { version = "0.3", features = ["suggestions", "color"] }
toml = "0.5"

sp-io = { git = "https://github.com/paritytech/substrate", branch = "master" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "master" }

substrate-archive = { path = "../../substrate-archive" }
