# Must be an absolute path to where polkadot chain data is stored 
polkadot_path = "/home/insipx/.local/share/polkadot/"

# Url to chain running in --pruning=archive
rpc_url = "ws://127.0.0.1:9944"

# How much should the read-only database keep in cache (MB) (required)
cache_size = 128

# Number of threads to dedicate for executing blocks
# Optional. If not specified, threads will be set
# to the default number of logical system threads
# More BlockWorkers requires that you also increase the number of WASM pages
# else the wasm executor will run out of memory. This also increases substrate-archives
# Generally, you want 32 pages per block worker
# memory usage
block_workers = 2
# Number of 64KB Heap Pages to allocate for WASM execution
wasm_pages = 256

db_host = "localhost"
db_port = "5432"
db_user = "archive"
# Can also be specified with DB_PASS environment variable
db_pass = "default"

# Names for the PostgreSQL databases for different chains
# Each chain will get it's own PostgreSQL database if run with that chain
# A fully synced Kusama PostgreSQL database (~2.8Million blocks) takes up around 70GB
# These variables can also be exposed with DB_NAME environment variable
westend_db = "westend-archive"
kusama_db = "kusama-db"
polkadot_db = "polkadot-archive"


